### PR TITLE
added Bootstrap 3 with schema.org Microdata view

### PR DESCRIPTION
**Pull request by petewarrior**

### CODE REVIEW

**Comment by petewarrior** [comment]
similar to [https://github.com/davejamesmiller/laravel-breadcrumbs/pull/83](url) but uses BreadcrumbList

**Comment by davejamesmiller** [comment]
Sorry I haven't got to this yet, but I do plan to merge it next time I have time to do a new release. Thanks!

**Comment by davejamesmiller** [comment]
**Laravel Breadcrumbs is no longer officially maintained**
Please [see the README file](https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/README.rst) for further details.

**Comment by davejamesmiller** [comment]
I’ve decided to [start working on Laravel Breadcrumbs again](https://davejamesmiller.com/2017/06/24/laravel-breadcrumbs-redux).

JSON-LD support will be [added in v4](https://github.com/davejamesmiller/laravel-breadcrumbs/pull/140). I decided not to include templates for Microdata or RDFa because I'd need too many different views to support all possible combinations ({Microdata, RDFa, None} * {Bootstrap 2, Bootstrap 3, Bootstrap 4}), JSON-LD seems simpler, and [Google now recommends JSON-LD](https://developers.google.com/search/docs/guides/intro-structured-data) in their documentation.

**Pull request closed without merging**
