### PR TITLE
breadcrumbs file configurable

### PR DESCRIPTION
**Pull request by xeno010**
make breadcrumbs file configurable

### CODE REVIEW

**Comment by eNzyOfficial** [comment]
Please add this to support 5.3

**Comment by davejamesmiller** [comment]
I've not yet decided whether to add the `file` option to the config, but I've [released v3.0.1](http://laravel-breadcrumbs.davejamesmiller.com/en/latest/changelog.html#v3-0-1-28-aug-2016) with Laravel 5.3 support (allows you to put the file in `routes/breadcrumbs.php` as suggested here) and I've also expanded the documentation on [defining breadcrumbs in a different file](http://laravel-breadcrumbs.davejamesmiller.com/en/latest/advanced.html#defining-breadcrumbs-in-a-different-file) which achieves the same thing.

**Comment by eNzyOfficial** [comment]
Awesome, thanks a lot!

**Comment by davejamesmiller** [comment]
**Laravel Breadcrumbs is no longer officially maintained**
Please [see the README file](https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/README.rst) for further details.

**Comment by davejamesmiller** [comment]
I’ve decided to [start working on Laravel Breadcrumbs again](https://davejamesmiller.com/2017/06/24/laravel-breadcrumbs-redux).

This will be [added in v4](https://github.com/davejamesmiller/laravel-breadcrumbs/pull/140).

**Pull request closed without merging**
