### PR TITLE
Added string class support

### PR DESCRIPTION
**Pull request by xeno010**
Add support for string classes (like routes)

This is the first step for cached Breadcrumbs.

*Example: breadcrumbs.php*
```php
<?php
/**
* The breadcrumbs.php
**/


Breadcrumbs::register('project-home', function($breadcrumbs, $param)
{
    $breadcrumbs->push('Home - ' . $param, '');
});
//Call add methode in ProjectBreadcrumbController class
Breadcrumbs::register('project-timeline', '\App\Breadcrumbs\ProjectBreadcrumbController@add');
//Call timeline methode in ProjectBreadcrumbController class
Breadcrumbs::register('project-timeline', \App\Breadcrumbs\ProjectBreadcrumbController::class.'@timeline');
//Call __invoke methode in ProjectBreadcrumbController class
Breadcrumbs::register('project-events', \App\Breadcrumbs\ProjectBreadcrumbController::class);
```

*Example: ProjectBreadcrumbController*
```php
<?php

namespace App\Breadcrumbs;

use DaveJamesMiller\Breadcrumbs\Generator;

class ProjectBreadcrumbController
{

    public function timeline(Generator $breadcrumbs, $time = '')
    {
        $breadcrumbs->push('Timeline- ' . $time, '');
    }

   public function add(Generator $breadcrumbs)
    {
        $breadcrumbs->push('Add');
    }

    function __invoke(Generator $breadcrumbs)
    {
        $breadcrumbs->push('Events', '');
    }
}
```

### CODE REVIEW

**Comment by davejamesmiller** [comment]
> This is the first step for cached Breadcrumbs

Have you verified that caching would actually speed it up? As discussed in [#112](https://github.com/davejamesmiller/laravel-breadcrumbs/issues/112#issuecomment-170452921) I have my doubts, but I'd like to see some benchmarks.

**Comment by xeno010** [comment]
The primary target is a better structure. I have more than 50 definitions in my breadcrumbs.php. 
I find "string class" better than "anonymous function" (by many definitions). And this is only a option

**Comment by davejamesmiller** [comment]
OK so ignoring the caching/speed issue, I think:

- The namespace should be optional, the same as in routes
- `Controller` is the wrong suffix to use, I'd suggest just `Breadcrumbs`
- Maybe they should be in the `Http` namespace, the same as `Controllers`
- If we're going to create a whole class, we should be able to skip the `$breadcrumbs` argument on each method
- We might as well skip `Breadcrumbs::register()` completely by combining it with #74 - register the breadcrumbs directly against routes

So that would give us something like this, with no `breadcrumbs.php` required:

```php
// routes/web.php
Route::get('forums/category/{category}', ['as' => 'forums.category',
    'uses' => 'ForumsController@category', 'breadcrumb' => 'ForumsBreadcrumbs@category']);

// app/Http/Breadcrumbs/ForumsBreadcrumbs.php
namespace App\Http\Breadcrumbs;

use App\Models\Category;
use DaveJamesMiller\Breadcrumbs\Breadcrumbs;

class ForumsBreadcrumbs extends Breadcrumbs
{
    public function category(Category $category)
    {
        $this->parent('home'); // Uses the 'home' route
        //OR $this->parent('HomeBreadcrumbs@index');
        $this->push($category->title, route('forums.category', $category->id));
    }
}
```

What do you think?

**Comment by xeno010** [comment]
That is a really cool idea.

I have implemented it.

TODO:
- [ ] add Unit-Tests

**Comment by xeno010** [comment]
Now supported:

```php
<?php
/**
* The breadcrumbs.php
**/
Breadcrumbs::register('AAA', function($breadcrumbs, $param)
{
    $breadcrumbs->push('Home - ' . $param, '');
});

Breadcrumbs::register('BBB', 'BBBBBreadcrumbs@add');

Breadcrumbs::register('CCC', '\Foo\Bar\CCCCBreadcrumbs@add')
```

```php
# routes.php

Route::get('forums/category/{category}', ['as' => 'forums.category',
    'uses' => 'ForumsController@category', 'breadcrumb' => 'ForumsBreadcrumbs@category']);

Route::get('forums/category/{category}', ['as' => 'forums.category',
    'uses' => 'ForumsController@category', 'breadcrumb' => '\Foo\Bar\ForumsBreadcrumbs@category']);
```

**Comment by davejamesmiller** [comment]
Thanks for this. Just wanted to update you - my current thought is to include this in the next major version, as it's a big change. I may make it the default and deprecate the old way - I need to think about that more and experiment with it on my own projects to see which feels more natural. And the documentation will need updating to explain how to use it. I don't expect I'll have time to do that for several weeks - say late October.

One more thing I want to look into - it seems in Laravel 5.3 the `['as' => 'name']` format is deprecated in favour of the [`->name('name')` chained method](https://laravel.com/docs/5.3/routing#named-routes). I'd like to dig around in the code to see if it's possible to add a `->breadcrumb('name')` method in the same way... Though on first look I don't think that's possible without replacing the whole `Router` instance.

**Comment by davejamesmiller** [comment]
**Laravel Breadcrumbs is no longer officially maintained**
Please [see the README file](https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/README.rst) for further details.

**Comment by davejamesmiller** [comment]
Sorry, I've decided I no longer have the time or motivation to continue supporting this package, so I won't be implementing this. Thanks for taking the time to implement it though - hopefully someone will fork the package and consider including this.

Another option I thought of is to keep the old `Breadcrumbs::register(...)` syntax but simply split the `breadcrumbs.php` file up into multiple files (e.g. `breadcrumbs/forums.php`, `breadcrumbs/pages.php`), rather than using classes. That is already supported by [overriding the `registerBreadcrumbs()` method](https://laravel-breadcrumbs.readthedocs.io/en/latest/advanced.html#defining-breadcrumbs-in-a-different-file).

**Comment by Decadence** [comment]
@davejamesmiller could you create last issue where people can decide who will fork and maintain your package?

**Comment by davejamesmiller** [comment]
https://github.com/davejamesmiller/laravel-breadcrumbs/issues/137

**Pull request closed without merging**
