### PR TITLE
Add method to get breadcrumb informations (Breadcrumbs::get())

### PR DESCRIPTION
**Pull request by nathan818fr**
(Useful to get current page title)

### CODE REVIEW

**Comment by davejamesmiller** [comment]
I'm not really sure what this does. Can you explain it please?

**Comment by nathan818fr** [comment]
This allows to retrieve information related to a breadcrumb.

By example, to retrieve a breadcrumb title, you can use:
```php
// Retrieve specific breadcrumb title:
$title = Breadcrumbs::get($breadcrumb_name, $breadcrumb_arg)->title;
// Or retrieve breadcrumb title associed to the current route:
$title = Breadcrumbs::get()->title;
```

```php
var_dump(Breadcrumbs::get());
// object(stdClass) (2) {
//     ["title"]=> string(4) "Home"
//     ["url"]=> string(27) "http://127.0.0.1/fr/home"
// }
```

**Comment by davejamesmiller** [comment]
OK, sounds good. It needs unit tests - if you can add them I'll merge it, otherwise I'll add them next time I'm working on it. Thanks!

**Comment by cdavid14** [comment]
Pull suggestion:

In **Manager.php**, add this function:


```
public function get(){
    $arr = $this->generator->toArray(); //Will get all breadcrumbs as array
    return $arr[count($arr)-1]; //Will return only the last breadcrumb (or the current)
}
```


And at blade template you can use

`{{ Breadcrumbs::get()->title }}`

to return current page title

Or at your controller, you can use
```
$title = Breadcrumbs::get()->title; 

var_dump($title);
//object(stdClass)#132 (4) { 
//    ["title"]=> string(6) "Home" 
//    ["url"]=> string(37) "http://localhost/laravel/public/panel" 
//    ["first"]=> bool(true) 
//    ["last"]=> bool(true) 
//};

```

cheers :+1:

**Comment by davejamesmiller** [comment]
**Laravel Breadcrumbs is no longer officially maintained**
Please [see the README file](https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/README.rst) for further details.

**Comment by davejamesmiller** [comment]
I’ve decided to [start working on Laravel Breadcrumbs again](https://davejamesmiller.com/2017/06/24/laravel-breadcrumbs-redux).

This will be [added in v4](https://github.com/davejamesmiller/laravel-breadcrumbs/pull/140) as `Breadcrumbs::current()`.

**Pull request closed without merging**
