### PR TITLE
Add unshift method to put crumbs at front of array

### PR DESCRIPTION
**Pull request by cviebrock**
We were needing this feature on a site in order to build up categories and subcategories, etc., when we could only traverse up the tree.

I'm sure there are other cases where you might want to add a crumb to the top of the stack.  :)

### CODE REVIEW

**Comment by cviebrock** [comment]
I also should have mentioned ... we're on Laravel 4, so this is just a PR against your `2.x` branch.  Feel free to add it to the L5 branch as well, if you think it's useful.

**Comment by davejamesmiller** [comment]
Out of interest, can you share your breadcrumbs.php code? There is an example in the docs where I traverse up the tree and it still works with `push()` as long as you call `parent()` first. Not that I'm against adding `unshift()` - just like to understand the use case.

There's a lot of duplication between the two methods, so one thing I'd do is add a new protected method `createBreadcrumb($title, $url, $data)` which contains the whole `(object) array(...)` part.

Cheers!

**Comment by cviebrock** [comment]
I saw the example you had, looping the array of `$category->ancestors`.  Sadly, the model I'm working with doesn't have that ... just a `parent` relation.  So, what I ended up doing is this (without using my new `unshift` method).

```php
Breadcrumbs::register('itemPage', function ($breadcrumbs, $page) {

	$breadcrumbs->parent('getIndex');

	$crumbData = [];
	$category = $page['category'];

	while ($category) {
		array_unshift($crumbData, [
			'name' => $category->category_name,
			'route' => route('getCategoryPage', [$category->url]),
			'extra' => [
				'alt' => $category->title
			]
		]);
		$category = $category->parent;
	}

	foreach ($crumbData as $data) {
		$breadcrumbs->push($data['name'], $data['route'], $data['extra']);
	}

	$breadcrumbs->push($page['title'], route('getItemPage));
});
```

With `unshift`, it gets a bit cleaner (although I have to `unshift` the parent as well, and do it after the loop to make sure it really goes to the top of the queue).

Thanks!

**Comment by davejamesmiller** [comment]
Try using a [recursive function](http://laravel-breadcrumbs.davejamesmiller.com/en/latest/defining.html#nested-categories) instead - that would greatly simplify it for you:

```php
Breadcrumbs::register('getCategoryPage', function ($breadcrumbs, $category) {
    if ($category->parent)
        $breadcrumbs->parent('getCategoryPage', $category->parent);
    else
        $breadcrumbs->parent('getIndex');

    $breadcrumbs->push($category->category_name, route('getCategoryPage', [$category->url]), ['alt' => $category->title]);
});

Breadcrumbs::register('itemPage', function ($breadcrumbs, $page) {
    $breadcrumbs->parent('getCategoryPage', $page['category']);
    $breadcrumbs->push($page['title'], route('getItemPage));
});
```

Alternatively, you could add a method to generate the ancestors array in the model as I did:

```php
protected function getAncestorsAttribute()
{
    if (!$this->parent)
        return [];

    $ancestors = $this->parent->ancestors;
    $ancestors[] = $this->parent;
    return $ancestors;
}
```

**Comment by davejamesmiller** [comment]
Any luck with that? I think it's generally a better solution than unshift, so I'm hesitant to add unshift and complicate things unless I have to...

**Comment by cviebrock** [comment]
Yeah, the recursive solution is much more elegant.  You can ignore my `unshift` hack.  :)

**Comment by davejamesmiller** [comment]
Cool :)

**Pull request closed without merging**
