### PR TITLE
Changed providers and aliases to current Larvel standards

### PR DESCRIPTION
**Pull request by danielgelling**

### CODE REVIEW

**Comment by davejamesmiller** [comment]
Thanks, I've been meaning to update that.

**Comment by danielgelling** [comment]
Hey,

I was looking for something an I've suddenly came accross that thing, jeez... you  have  to take  a look <http://discount.adultdesignstudio.com/e3vyz>

Cheers, info@danielgelling.nl

**Comment by danielgelling** [comment]
Hello, 


I just wanted to share some interesting thoughts about amazing  people I met yesterday, please read more here <http://simple.stereogearjunkies.com/e3ixg>

Bests, info

**Comment by danielgelling** [comment]
Hello friend, 
I have to show  you something  that  I  can't  understand, can you tell me what's that? Take a look here <http://balance.vlbconsult.com/e3tjkbsn>
info

**Comment by davejamesmiller** [comment]
Locked due to spam emails

**Pull request merged**
