### PR TITLE
Structured data attributes

### PR DESCRIPTION
**Pull request by baribadamshin**

### CODE REVIEW

**Comment by davejamesmiller** [comment]
Thanks for this. The [Google link](https://developers.google.com/structured-data/breadcrumbs) from #79 seems to recommend http://schema.org/BreadcrumbList rather than http://data-vocabulary.org/Breadcrumb that's used here. Do you know any more about this? As far as I can tell, schema.org is more commonly used - but I'm no expert in that...

**Comment by baribadamshin** [comment]
A couple of months ago, Google recommend using http://data-vocabulary.org/Breadcrumb, that's why I used this method. I'll create one more view for http://schema.org/BreadcrumbList

**Comment by dnixx** [comment]
Yeah, Google recently changed their recommendation to schema.org :)
Thanks for this!

**Comment by davejamesmiller** [comment]
**Laravel Breadcrumbs is no longer officially maintained**
Please [see the README file](https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/README.rst) for further details.

**Comment by davejamesmiller** [comment]
I’ve decided to [start working on Laravel Breadcrumbs again](https://davejamesmiller.com/2017/06/24/laravel-breadcrumbs-redux).

JSON-LD support will be [added in v4](https://github.com/davejamesmiller/laravel-breadcrumbs/pull/140). I decided not to include templates for Microdata or RDFa because I'd need too many different views to support all possible combinations ({Microdata, RDFa, None} * {Bootstrap 2, Bootstrap 3, Bootstrap 4}), JSON-LD seems simpler, and [Google now recommends JSON-LD](https://developers.google.com/search/docs/guides/intro-structured-data) in their documentation.

**Pull request closed without merging**
