### PR TITLE
Updating the service provider

### PR DESCRIPTION
**Pull request by arcanedev-maroc**

### CODE REVIEW

**Comment by davejamesmiller** [comment]
Why? And No.

**Comment by arcanedev-maroc** [comment]
For the package Development, the only method that's should be in the `register` method is the `mergeConfigFrom`, and the others in the `boot` method.

This is an optimization when the service provider is `registered` vs `booted`.

**Comment by davejamesmiller** [comment]
And why all the other changes like reordering, reformatting, and renaming?

**Comment by arcanedev-maroc** [comment]
IMO, the main other for a service provider is `register` > `boot` > `provides`.

And for the `registerBreadcrumbs` method, i think the `loadBreadcrumbs` is the proper name instead `registerBreadcrumbs` (it has the register prefix like the register of the service provider, registering the services).

**Comment by davejamesmiller** [comment]
OK, thanks for taking the time to check and update them.

Do you have any use case that actually calls `register()` without calling `boot()`, and does it actually make any difference where the functions calls go? Especially when loading is deferred, so both are usually called at the same time. Not that I won't fix it - but I'll probably wait until the next major release to change it.

With regard to formatting - in my mind `provides` comes first. `provides()` is used for lazy-loading, and `register()` isn't called until after lazy-loading happens. But in any case please don't bundle changes that are purely preference into an unrelated PR, especially with no explanation.

`registerBreadcrumbs()` is not called that because it's called from `register()` - it's because the LB method to register breadcrumbs was called `Breadcrumbs::register()` until recently (now renamed to `Breadcrumbs::for()`) - so no it doesn't need to be changed.

**Pull request closed without merging**
