### PR TITLE
v4.0 - Laravel 5.5 support, package auto-discovery, various changes & new features

### PR DESCRIPTION
**Pull request by davejamesmiller**
Also removing backwards compatibility and changing some internal workings, so this will be a major release (4.x).

See the [Changelog](https://github.com/davejamesmiller/laravel-breadcrumbs/tree/4.x#changelog) for details.

Still to do:

- [x] Wait until Laravel 5.5 is released
- [x] Update Laravel documentation links in README from 5.4 to 5.5
- [x] Update installation instructions
- [ ] Merge into master
- [ ] Release it
- [ ] Delete 4.x branch (to avoid confusion with master branch)

### CODE REVIEW

**Comment by JayBizzle** [comment]
Good stuff 👍 

Does this mean this package is no longer 'Abandoned'?

**Comment by davejamesmiller** [comment]
Yes - https://davejamesmiller.com/2017/06/24/laravel-breadcrumbs-redux

**Comment by JayBizzle** [comment]
Brilliant, thanks @davejamesmiller 

Agree with all your sentiments in that blog post, it's sometimes a very thankless task being an OSS maintainer 👍 

So, thanks :)

**Comment by bloggervista** [comment]
When will this be merged?

**Comment by davejamesmiller** [comment]
@JayBizzle Thanks :)

@bloggervista Thanks for helping prove the point about it being a thankless task. I think I might add "Ignore people who don't say please / thank you or show any gratitude" to the list. It'll be merged when I'm ready to merge it. Probably not until Laravel 5.5 is released ([ETA August](https://twitter.com/taylorotwell/status/879032992064294913)).

**Comment by decadence** [comment]
I think we should not ask WHEN it will be merged and just say thanks God and @davejamesmiller it will be merged at all :)

**Comment by bloggervista** [comment]
Thanks :) 
I looked documentation again from scratch and I find this update really good :)

**Comment by davejamesmiller** [comment]
@bloggervista Thanks 😃 

I think this is finished now. I'm going to leave it on the 4.x branch until around the time Laravel 5.5 is released in case anything changes that's not compatible.

https://github.com/davejamesmiller/laravel-breadcrumbs/tree/4.x#changelog

If anyone finds any bugs or has suggestions for improving the documentation please let me know or make a PR against the 4.x branch.

**Comment by Omranic** [comment]
That's really amazing news, glad to see this package back to life.
Thank you @davejamesmiller, really appreciate your efforts 👍

**Comment by davejamesmiller** [comment]
v4.0.0 is now officially released, ready for Laravel 5.5's release.

**Pull request merged**
